export const mockUsers = [
  {
    fullName: 'Hoàng Lưu (Customer)',
    email: 'customer@gmail.com',
    password: 'password123',
    phone: '0905123456',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    role: 'USER',
    status: 'ACTIVE',
    preferences: {
      favoriteCategories: ['CAFE', 'RESTAURANT', 'MILK_TEA', 'BBQ'],
      priceRange: { min: 30000, max: 500000 },
      preferredAreas: ['Hải Châu', 'Sơn Trà', 'Thanh Khê'],
    },
  },
  {
    fullName: 'Nguyễn Quản Trị (Admin)',
    email: 'admin@gmail.com',
    password: 'adminpassword',
    phone: '0909999999',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    role: 'ADMIN',
    status: 'ACTIVE',
  },
  {
    fullName: 'Lê Văn Chủ Quán (Merchant)',
    email: 'owner@gmail.com',
    password: 'ownerpassword',
    phone: '0908888888',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    role: 'MERCHANT',
    status: 'ACTIVE',
  },
  {
    fullName: 'Phạm Thị Nhân Viên (Staff)',
    email: 'staff@gmail.com',
    password: 'staffpassword',
    phone: '0907777777',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
    role: 'STAFF',
    status: 'ACTIVE',
  },
];

export const mockBusinesses = [
  {
    name: 'Highlands Coffee - Nguyễn Văn Linh',
    slug: 'highlands-coffee-nguyen-van-linh',
    description: 'Thương hiệu cà phê hàng đầu Việt Nam với Phin Sữa Đá đượm vị truyền thống và Freeze Trà Xanh mát lạnh.',
    categories: ['CAFE', 'DESSERT', 'BAKERY'],
    logoUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    priceRange: { min: 29000, max: 75000 },
    vibes: ['Yên tĩnh / Làm việc', 'Hiện đại / Sang trọng', 'Ngoài trời / Sân vườn'],
    purposes: ['Họp nhóm / Học bài', 'Gặp gỡ bạn bè', 'Ăn một mình / Chill'],
    status: 'APPROVED',
    ratingSummary: { average: 4.8, totalReviews: 128 },
    branchInfo: {
      name: 'Highlands Coffee - Chi nhánh 186 Nguyễn Văn Linh',
      street: '186 Nguyễn Văn Linh',
      ward: 'Nam Dương',
      district: 'Hải Châu',
      city: 'Đà Nẵng',
      coordinates: [108.2165, 16.0605],
      phone: '0236 3888 999',
      amenities: ['WIFI', 'PARKING', 'AIR_CONDITIONING', 'OUTDOOR_SEATING'],
    },
    products: [
      {
        name: 'Phin Sữa Đá (Đặc Sản)',
        category: 'CAFE',
        description: 'Cà phê phin đậm đà kết hợp với sữa đặc béo ngậy truyền thống.',
        price: 39000,
        imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
        options: [
          { name: 'Size', required: true, values: [{ name: 'S', price: 0 }, { name: 'M', price: 6000 }, { name: 'L', price: 10000 }] },
          { name: 'Đá', required: false, values: [{ name: '100% Đá', price: 0 }, { name: '50% Đá', price: 0 }, { name: 'Không Đá', price: 0 }] },
        ],
      },
      {
        name: 'Freeze Trà Xanh Kèm Thạch',
        category: 'CAFE',
        description: 'Thức uống đá xay trà xanh thượng hạng kết hợp thạch giòn sần sật.',
        price: 55000,
        imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=400&q=80',
        options: [
          { name: 'Size', required: true, values: [{ name: 'M', price: 0 }, { name: 'L', price: 10000 }] },
        ],
      },
      {
        name: 'Bánh Mì Que Cột Đèn Hai Phong',
        category: 'BAKERY',
        description: 'Bánh mì giòn rụm kẹp pate thơm béo đượm vị.',
        price: 25000,
        imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=400&q=80',
        options: [],
      },
    ],
  },
  {
    name: "Pizza 4P's - Bạch Đằng Đà Nẵng",
    slug: 'pizza-4ps-bach-dang',
    description: 'Nhà hàng Pizza nướng củi nổi tiếng thế giới với phô mai Burrata tươi tự sản xuất tại Đà Lạt.',
    categories: ['RESTAURANT', 'DESSERT'],
    logoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    priceRange: { min: 150000, max: 650000 },
    vibes: ['Lãng mạn / Hẹn hò', 'Hiện đại / Sang trọng', 'Ấm cúng / Gia đình'],
    purposes: ['Hẹn hò cặp đôi', 'Bữa ăn gia đình', 'Tiếp khách / Công việc', 'Tổ chức sinh nhật / Tiệc'],
    status: 'APPROVED',
    ratingSummary: { average: 4.9, totalReviews: 240 },
    branchInfo: {
      name: "Pizza 4P's - Chi nhánh 08 Bạch Đằng",
      street: '08 Bạch Đằng',
      ward: 'Thạch Thang',
      district: 'Hải Châu',
      city: 'Đà Nẵng',
      coordinates: [108.2235, 16.0725],
      phone: '028 3622 0500',
      amenities: ['WIFI', 'RIVER_VIEW', 'AIR_CONDITIONING', 'PRIVATE_ROOM'],
    },
    products: [
      {
        name: 'Pizza 4 Cheese Kèm Mật Ong Tự Nhiên',
        category: 'RESTAURANT',
        description: 'Pizza nướng củi kết hợp 4 loại phô mai tươi béo ngậy rưới mật ong thơm ngọt.',
        price: 265000,
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80',
        options: [
          { name: 'Đế bánh', required: true, values: [{ name: 'Đế Mỏng Giòn', price: 0 }, { name: 'Đế Dày Mềm', price: 0 }] },
        ],
      },
      {
        name: 'Mì Ý Cua Sốt Kem Cà Chua',
        category: 'RESTAURANT',
        description: 'Mì Ý tươi kết hợp thịt cua biển nguyên con và sốt kem cà chua béo thơm.',
        price: 245000,
        imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281273?auto=format&fit=crop&w=400&q=80',
        options: [],
      },
    ],
  },
  {
    name: 'Lẩu & Nướng K-Pub Korean BBQ',
    slug: 'k-pub-korean-bbq-da-nang',
    description: 'Thương hiệu nướng đường phố Hàn Quốc phong cách Pub hiện đại với thịt heo gói sương nướng sốt cay.',
    categories: ['BBQ', 'BUFFET', 'RESTAURANT'],
    logoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    priceRange: { min: 199000, max: 399000 },
    vibes: ['Sôi động / Nhộn nhịp', 'Hiện đại / Sang trọng', 'Rộng rãi / Nhóm đông'],
    purposes: ['Tụ tập bạn bè', 'Bữa ăn gia đình', 'Tổ chức sinh nhật / Tiệc'],
    status: 'APPROVED',
    ratingSummary: { average: 4.7, totalReviews: 95 },
    branchInfo: {
      name: 'K-Pub - Chi nhánh 304 Võ Nguyên Giáp',
      street: '304 Võ Nguyên Giáp',
      ward: 'Mỹ An',
      district: 'Ngũ Hành Sơn',
      city: 'Đà Nẵng',
      coordinates: [108.2465, 16.0512],
      phone: '0236 7300 500',
      amenities: ['WIFI', 'SEA_VIEW', 'AIR_CONDITIONING', 'FREE_SIDE_DISH'],
    },
    products: [
      {
        name: 'Buffet Nướng Thang Mới K-Pub (Vé Người Lớn)',
        category: 'BBQ',
        description: 'Thưởng thức không giới hạn 30+ món thịt nướng Bò Mỹ, Heo sốt Cay và quầy Line Panchan cực đỉnh.',
        price: 299000,
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
        options: [],
      },
      {
        name: 'Lẩu Kim Chi Hải Sản Hàn Quốc',
        category: 'BUFFET',
        description: 'Nước lẩu chua cay đậm đà kèm tôm, mực, ngao tươi và nấm kim châm.',
        price: 189000,
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=400&q=80',
        options: [],
      },
    ],
  },
  {
    name: 'Trà Sữa Gong Cha - Nguyễn Văn Thoại',
    slug: 'gong-cha-nguyen-van-thoai',
    description: 'Thương hiệu trà sữa Hoàng Gia Đài Loan nổi tiếng với lớp Milk Foam sánh mịn mặn béo.',
    categories: ['MILK_TEA', 'DESSERT'],
    logoUrl: 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=800&q=80',
    priceRange: { min: 38000, max: 85000 },
    vibes: ['Check-in sống ảo', 'Yên tĩnh / Làm việc', 'Ấm cúng / Gia đình'],
    purposes: ['Gặp gỡ bạn bè', 'Họp nhóm / Học bài', 'Thư giãn cuối tuần', 'Ăn một mình / Chill'],
    status: 'APPROVED',
    ratingSummary: { average: 4.8, totalReviews: 160 },
    branchInfo: {
      name: 'Gong Cha - Chi nhánh 225 Nguyễn Văn Thoại',
      street: '225 Nguyễn Văn Thoại',
      ward: 'Phước Mỹ',
      district: 'Sơn Trà',
      city: 'Đà Nẵng',
      coordinates: [108.2412, 16.0558],
      phone: '0236 3945 678',
      amenities: ['WIFI', 'AIR_CONDITIONING', 'TAKE_AWAY'],
    },
    products: [
      {
        name: 'Trà Sữa Trân Châu Đen Hoàng Gia',
        category: 'MILK_TEA',
        description: 'Trà đen Ceylon thơm đậm đặn hòa quyện vị sữa béo và trân châu dẻo ngọt.',
        price: 49000,
        imageUrl: 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=400&q=80',
        options: [
          { name: 'Size', required: true, values: [{ name: 'M', price: 0 }, { name: 'L', price: 10000 }] },
          { name: 'Đường', required: false, values: [{ name: '100%', price: 0 }, { name: '70%', price: 0 }, { name: '50%', price: 0 }] },
          { name: 'Topping', required: false, values: [{ name: 'Milk Foam Mặn', price: 12000 }, { name: 'Pudding Flan', price: 10000 }] },
        ],
      },
    ],
  },
  {
    name: 'Hải Sản Bé Mặn - Võ Nguyên Giáp',
    slug: 'hai-san-be-man-da-nang',
    description: 'Quán hải sản tươi sống nổi tiếng nhất ven biển Đà Nẵng, chế biến tại chỗ ngon khó cưỡng.',
    categories: ['RESTAURANT', 'BBQ'],
    logoUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=400&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    priceRange: { min: 100000, max: 600000 },
    vibes: ['Ngoài trời / Sân vườn', 'Rộng rãi / Nhóm đông', 'Vỉa hè / Đường phố'],
    purposes: ['Bữa ăn gia đình', 'Tụ tập bạn bè', 'Tiếp khách / Công việc'],
    status: 'APPROVED',
    ratingSummary: { average: 4.6, totalReviews: 310 },
    branchInfo: {
      name: 'Hải Sản Bé Mặn - Chi nhánh Lô 11 Võ Nguyên Giáp',
      street: 'Lô 11 Võ Nguyên Giáp',
      ward: 'Mỹ An',
      district: 'Ngũ Hành Sơn',
      city: 'Đà Nẵng',
      coordinates: [108.2488, 16.0592],
      phone: '0905 207 848',
      amenities: ['PARKING', 'SEA_VIEW', 'OPEN_AIR'],
    },
    products: [
      {
        name: 'Tôm Hùm Bông Nướng Bơ Tỏi (500g)',
        category: 'RESTAURANT',
        description: 'Tôm hùm bông sống nướng bơ tỏi thơm nức mũi.',
        price: 450000,
        imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=400&q=80',
        options: [],
      },
      {
        name: 'Cua Huỳnh Đế Hấp Sả Gừng (Kg)',
        category: 'RESTAURANT',
        description: 'Cua biển thịt chắc ngọt chấm muối ớt xanh đặc sản Đà Nẵng.',
        price: 380000,
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
        options: [],
      },
    ],
  },
];
